2022-05-01 18:04:21,173 - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "c:/hakaton/1mayhack/bot.py", line 51, in true
    reply_markup=button
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 531, in send_message
    protect_content=protect_content,
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\ext\extbot.py", line 209, in _message
    protect_content=protect_content,
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 296, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\utils\request.py", line 366, in post
    **urlopen_kwargs,
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
2022-05-01 18:04:37,989 - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "c:/hakaton/1mayhack/bot.py", line 51, in true
    reply_markup=button
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 531, in send_message
    protect_content=protect_content,
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\ext\extbot.py", line 209, in _message
    protect_content=protect_content,
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 296, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\utils\request.py", line 366, in post
    **urlopen_kwargs,
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
2022-05-01 18:04:52,837 - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\ext\dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\ext\handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "c:/hakaton/1mayhack/bot.py", line 51, in true
    reply_markup=button
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 531, in send_message
    protect_content=protect_content,
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\ext\extbot.py", line 209, in _message
    protect_content=protect_content,
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 336, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\bot.py", line 296, in _post
    f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\utils\request.py", line 366, in post
    **urlopen_kwargs,
  File "C:\hakaton\1mayhack\venv\lib\site-packages\telegram\utils\request.py", line 279, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
2022-05-01 18:08:09,545 - ERROR - Ответ на вопрос не получен, Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
2022-05-01 18:09:00,607 - ERROR - Ответ на вопрос не получен, Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
2022-05-01 18:15:38,780 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 197
2022-05-01 18:17:19,815 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 197
2022-05-01 18:17:45,001 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 197
2022-05-01 18:17:53,299 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 197
2022-05-01 18:17:56,149 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 197
2022-05-01 18:17:59,377 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 197
2022-05-01 18:18:12,444 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 197
2022-05-01 18:20:11,781 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 183
2022-05-01 18:20:20,855 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 183
2022-05-01 18:22:31,763 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 183
2022-05-01 18:22:47,261 - ERROR - Ответ на вопрос не получен, Can't parse entities: unexpected end of name token at byte offset 183
